"""Added pwd

Revision ID: b16deff82b1d
Revises: f16e321ce26d
Create Date: 2023-02-26 11:57:20.906501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16deff82b1d'
down_revision = 'f16e321ce26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
